name: Setup Environment
description: Setup environment
inputs:
  nix_cache_private_key:
    required: false
    description: Private key for Nix cache

  s3_access_key:
    required: false
    description: Access key for S3 bucket

  s3_secret_key:
    required: false
    description: Secret key for S3 bucket

  sccache_enabled:
    required: true
    description: Whether to enable sccache

  shell:
    required: true
    description: "Shell to use"
runs:
  using: "composite"
  steps:
    - name: Setup nix build paths file
      shell: bash
      env:
        NIX_CACHE_URL: s3://${{ env.S3_BUCKET }}/cache/nix?endpoint=${{ env.S3_ENDPOINT }}&scheme=https&compression=zstd&parallel-compression=true
      run: |
        echo "NIX_CACHE_URL=${NIX_CACHE_URL}" >> $GITHUB_ENV

    - name: Setup s3 credentials
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.s3_access_key || env.PUBLIC_S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3_secret_key || env.PUBLIC_S3_SECRET_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV

    - name: Setup nix cache private key
      if: inputs.nix_cache_private_key != ''
      shell: bash
      env:
        NIX_CACHE_PRIVATE_KEY: ${{ inputs.nix_cache_private_key }}
      run: |
        printenv NIX_CACHE_PRIVATE_KEY >> /tmp/nix-cache-key.pem

    - name: Nix cache upload
      uses: gacts/run-and-post-run@v1
      if: inputs.nix_cache_private_key != '' && inputs.s3_access_key != '' && inputs.s3_secret_key != ''
      with:
        post: exec ${{ github.workspace }}/.github/scripts/nix-upload-cache.sh

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          max-jobs = auto
          http-connections = 128
          connect-timeout = 5
          substituters = https://cache.nixos.org https://ci-cache.troymoder.dev/cache/nix
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= troy-crates-nix-cache:Gzil33SGyR5pzjFPe1l4ACZy2lfXi3Y5R5cO6BmOwkE=⏎
          post-build-hook = ${{ github.workspace }}/.github/scripts/nix-post-build-hook.sh

    - name: Setup sccache
      if: inputs.sccache_enabled == 'true'
      uses: ./.github/actions/setup-sccache
      with:
        shell: ${{ inputs.shell }}

    - name: Setup shell
      shell: ${{ inputs.shell }}
      run: |
        echo "activated shell"
