name: CI

on:
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: &read-permissions
      contents: read
    defaults: &defaults
      run:
        shell: ${{ github.workspace }}/.github/scripts/nix-shell.sh {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - &setup-nix
        name: Setup environment
        uses: troymoder/shared-actions/setup-nix@0445b4839de516226e314213dcb15fe4461109c3
        with:
          nix_cache_private_key: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}
          nix_cache_public_key: ${{ vars.NIX_CACHE_PUBLIC_KEY }}
          s3_bucket: ${{ vars.S3_CACHE_BUCKET }}
          s3_endpoint: ${{ vars.S3_CACHE_ENDPOINT }}
          s3_public_url: ${{ vars.S3_CACHE_PUBLIC_URL }}
          s3_access_key: ${{ secrets.S3_CACHE_BUCKET_ACCESS_KEY || vars.S3_CACHE_BUCKET_PUBLIC_ACCESS_KEY }}
          s3_secret_key: ${{ secrets.S3_CACHE_BUCKET_ACCESS_SECRET_KEY || vars.S3_CACHE_BUCKET_PUBLIC_ACCESS_SECRET_KEY }}

      - &setup-sccache
        name: Setup sccache
        uses: troymoder/shared-actions/setup-sccache@0445b4839de516226e314213dcb15fe4461109c3
        with:
          s3_bucket: ${{ vars.S3_CACHE_BUCKET }}
          s3_endpoint: ${{ vars.S3_CACHE_ENDPOINT }}
          sccache_command: ${{ github.workspace }}/.github/scripts/nix-shell.sh sccache

      - name: Run tests
        run: just test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/nextest/**/junit.xml
          report_type: test_results
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  fmt:
    name: Format
    runs-on: ubuntu-latest
    permissions: *read-permissions
    defaults: *defaults
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - *setup-nix

      - name: Check formatting
        run: just fmt

      - name: Check for changes
        run: git diff --exit-code

  sync-readme:
    name: Sync README
    runs-on: ubuntu-latest
    permissions: *read-permissions
    defaults: *defaults
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - *setup-nix

      - *setup-sccache

      - name: Sync README
        run: just sync-readme-test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions: *read-permissions
    defaults: *defaults
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - *setup-nix

      - *setup-sccache

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    permissions: *read-permissions
    defaults: *defaults
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - *setup-nix

      - *setup-sccache

      - name: Check documentation
        run: just doc

  status:
    name: Status
    runs-on: ubuntu-latest
    permissions: *read-permissions
    needs: [fmt, sync-readme, clippy, test, doc]
    if: ${{ !cancelled() }}
    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
