name: Release publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: release-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-publish:
    name: Release publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'troymoder' }}
    environment: crates publish
    permissions:
      contents: write
    defaults:
      run:
        shell: ${{ github.workspace }}/.github/scripts/nix-shell.sh {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: troymoder/shared-actions/setup-nix@0445b4839de516226e314213dcb15fe4461109c3
        with:
          nix_cache_private_key: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}
          nix_cache_public_key: ${{ vars.NIX_CACHE_PUBLIC_KEY }}
          s3_bucket: ${{ vars.S3_CACHE_BUCKET }}
          s3_endpoint: ${{ vars.S3_CACHE_ENDPOINT }}
          s3_public_url: ${{ vars.S3_CACHE_PUBLIC_URL }}
          s3_access_key: ${{ secrets.S3_CACHE_BUCKET_ACCESS_KEY || vars.S3_CACHE_BUCKET_PUBLIC_ACCESS_KEY }}
          s3_secret_key: ${{ secrets.S3_CACHE_BUCKET_ACCESS_SECRET_KEY || vars.S3_CACHE_BUCKET_PUBLIC_ACCESS_SECRET_KEY }}

      - name: Setup sccache
        uses: troymoder/shared-actions/setup-sccache@0445b4839de516226e314213dcb15fe4461109c3
        with:
          s3_bucket: ${{ vars.S3_CACHE_BUCKET }}
          s3_endpoint: ${{ vars.S3_CACHE_ENDPOINT }}
          sccache_command: ${{ github.workspace }}/.github/scripts/nix-shell.sh sccache
