name: Release PR

on:
  schedule:
    - cron: "30 10 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: release-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    environment: release pr
    if: ${{ github.repository_owner == 'troymoder' }}
    permissions:
      contents: read
    defaults:
      run:
        shell: ${{ github.workspace }}/.github/scripts/nix-shell.sh bash -e {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: troymoder/shared-actions/setup-nix@b114355b5a126b78c9e19920afa01075a32ee39e
        with:
          nix_cache_private_key: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}
          nix_cache_public_key: ${{ vars.NIX_CACHE_PUBLIC_KEY }}
          s3_bucket: ${{ vars.S3_CACHE_BUCKET }}
          s3_endpoint: ${{ vars.S3_CACHE_ENDPOINT }}
          s3_public_url: ${{ vars.S3_CACHE_PUBLIC_URL }}
          s3_access_key: ${{ secrets.S3_CACHE_BUCKET_ACCESS_KEY || vars.S3_CACHE_BUCKET_PUBLIC_ACCESS_KEY }}
          s3_secret_access_key: ${{ secrets.S3_CACHE_BUCKET_SECRET_ACCESS_KEY || vars.S3_CACHE_BUCKET_PUBLIC_SECRET_ACCESS_KEY }}

      - name: Setup sccache
        uses: troymoder/shared-actions/setup-sccache@b114355b5a126b78c9e19920afa01075a32ee39e
        with:
          s3_bucket: ${{ vars.S3_CACHE_BUCKET }}
          s3_endpoint: ${{ vars.S3_CACHE_ENDPOINT }}
          sccache_command: ${{ github.workspace }}/.github/scripts/nix-shell.sh sccache

      - name: Update crates
        run: release-plz update > ${{ runner.temp }}/release-body.txt

      - name: Sync README
        run: just sync-readme

      - name: Format
        run: just fmt

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate GitHub Token
        if: ${{ steps.changes.outputs.has_changes == 'true' }}
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create PR
        if: ${{ steps.changes.outputs.has_changes == 'true' }}
        uses: peter-evans/create-pull-request@v8
        with:
          title: "chore: release"
          commit-message: "chore: release"
          body-path: ${{ runner.temp }}/release-body.txt
          branch: release-pr
          labels: release
          token: ${{ steps.app-token.outputs.token }}
